server:
  port: 7000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  application:
    name: oik
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:13306/oik?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://101.42.151.233:13306/oik?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://101.42.224.188:13306/oik?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  #  注意缩进
  #  datasource:
  #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    url: jdbc:sqlserver://localhost:1433;DatabaseName=test_name
  #    username: sa
  #    password: Fyy@12345678
  redis:
    #    host: 127.0.0.1
#    host: 101.42.151.233
    host: 101.42.224.188
    port: 16379
    password: '000415'
#    sentinel:
#      master: master
#      nodes:
#        - 101.42.224.188:16379
#        - 101.42.224.188:26379
#        - 101.42.224.188:36379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    timeout: 5000
  jackson:
    time-zone: Asia/Shanghai
    #    generator:
    #      write_numbers_as_strings: true # 数字返回json 转成string 类型
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.oik.dao.entity # 别名扫描包
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/oik/dao/**/*.xml

mybatis-plus-join:
  #是否打印 mybatis plus join banner 默认true
  banner: true
  #全局启用副表逻辑删除(默认true) 关闭后关联查询不会加副表逻辑删除
  sub-table-logic: true
  #拦截器MappedStatement缓存(默认true)
  ms-cache: true
  #表别名(默认 t)
  table-alias: t

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: "shiro_test"
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

#oss:
#  access-id:
#  access-key:
#  end-point:
#  bucket:
#  host:






